In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import scipy.stats as sps
from sympy import *
from matplotlib import cm
plt.style.use('ggplot')
%matplotlib inline

def scan_from_csv(filename,header=None):
    if not header:
        return pd.read_csv(filename,na_values='None')
    else:
        return pd.read_csv(filename,na_values='None',header=-1)

def write_answer_to_file(answer,file):
    with open(file, 'w') as answer_file:  
        answer_file.write(answer)

In [52]:
X_train = pd.read_csv('hw11t4v0_train.txt',delimiter='\\s+',header=-1)
y_train = pd.read_csv('hw11t4v0_target.txt',delimiter='\\s+',header=-1)
X_test = pd.read_csv('hw11t4v0_test.txt',delimiter='\\s+',header=-1)
y_test = pd.read_csv('hw11t4v0_target_test.txt',delimiter='\\s+',header=-1)

In [53]:
X_train.head()

0      1      2      3      4      5      6      7      8      9
0  3.207  0.966 -0.047 -0.124 -0.283  0.409 -1.882 -3.760 -7.582  4.655
1 -0.110  0.063  0.082  0.127 -0.463 -0.253 -3.869  1.167  1.980  0.466
2  3.671 -1.043 -1.647  1.070 -0.075 -0.255 -0.952 -4.132 -2.808  1.147
3  0.191 -1.138  1.178  0.303 -0.969 -0.123  3.220  1.246  0.807 -0.068
4  3.141  1.167  0.250 -0.368 -0.735  0.389 -0.325 -2.166 -2.377 -0.970

воспользуемся t-sne чтобы понизить размерность, визуализировать данные, возможно, что-то будет видно

In [6]:
from sklearn.manifold import TSNE

In [18]:
model = TSNE(n_components=2, random_state=0)

In [19]:
np.set_printoptions(suppress=True)

In [54]:
train_trans = model.fit_transform(X_train,y_train)

array([ 12129.3,  12117.9,  12127.9,  12126.4,  12169.4,  12118.9,
        12660.2,  12522.9,  12160.5,  12132.9,  12069.6,  12132.7,
        11939.3,  12126.5,  12001.1,  12110.2,  12113.9,  12584.8,
        10117. ,  12121.5,  12003.8,  12385.9,  12149.6,  12107.9,
        12050.1,  12098.4,  12140.8,  11908. ,  11965.5,  12140.6,
        12035.9,  12252. ,  12085.6,  12038.3,  12117.7,  12117.4,
        12115.8,  12124.2,  12129.9,  11908.9,  12133.4,  12073.7,
        12153.5,  12138.3,  12119.2,  11897.1,  12110. ,  12109.9,
        12123.1,  12089.8,  12118.2,  12094.9,  12108.7,  12122.2,
        12127.8,  12030. ,  12123.8,  12102.7,  12095.6,  12103.1,
        12121.6,  12106.7,  12112.1,  12123.8,  12256.6,  12249.1,
        12145.4,  12141.3,  12119.5,  12138.1,  12135.2,  12115.9,
        12129.6,  12160.6,  12087. ,  12132. ,  12137.7,  12140.4,
        12126.9,  12113.2,  12071.8,  12097. ,  12147. ,  12104.2,
        12181. ,  12119.2,  12093.2,  12094.9,  12130.4,  1213

In [60]:
gridsize=30
y = np.array(y_train).ravel()
plt.plot(train_trans[:,0],train_trans[:,1],c= (y - np.min(y))/np.abs(np.max(y)))

ValueError: RGBA sequence should have length 3 or 4

In [32]:
x = sps.norm.rvs(size=(3,2))

In [33]:
x

array([[ 0.3, -0.6],
       [-0.1,  1.1],
       [-1.3,  0.6]])

In [37]:
x[:,1]

array([-0.6,  1.1,  0.6])